### ISSUE TITLE
"Help" not loading

### ISSUE THREAD

**Issue by rperlin-ela** [Language-Mapping/language-map#129]
## Summary

"Help" seems not to load/appear sometimes, possibly when the user has had their screen open for a while — clicking "Help" just returns a kind of semi-blacked out map. On refresh, it loads fine.

### Screenshots

![Screen Shot 2020-11-07 at 9 12 22 AM (2)](https://user-images.githubusercontent.com/52076788/98443466-6cc87280-20d9-11eb-9b70-f62540672d06.png)

**Comment by abettermap** [comment]
same with About. i think it's how i'm pre-downloading it. i'll try setting it to just load as normal instead. might be a small lag but that's better than a bug!

also i'd like to lump in the `i` and `?` into panel title bar and related things as suggested in #128.

**Comment by abettermap** [comment]
I believe I fixed this but it's a tricky one to test due to the intermittent nature. I can tell it's doing something though because when I leave the browser or page and come back, there's the transparent black "loading" overlay (sans text) for a second or two, regardless of how long I was gone and regardless of what page I was at. It's doing what I intended now (querying the WP site when I return to the page to keep the content from being stale) and I think the short delay is a very minor tradeoff since users coming back and forth to the site repeatedly in a short time period seems kinda low priority. Either they're distracted by notifications or we're not doing a good enough job of keeping their interest. 🥱
