### ISSUE TITLE
Show by "None (hide layer)" crashes the map?

### ISSUE THREAD

**Issue by rperlin-ela** [Language-Mapping/language-map#169]
## Summary

Seems straightforward: selecting "None" leads to a delay, then a message that it's loading legend info, and then comes the familiar error (see attached). Tried Firefox and Safari, desktop and mobile, same result. Could it be that we need something in AT > Schema for when the legend is not World Region, Size, or Status?

<img width="1440" alt="Screen Shot 2021-01-13 at 7 08 51 PM" src="https://user-images.githubusercontent.com/52076788/104527574-0c6f1900-55d3-11eb-9f02-0e87573d3cea.png">

**Comment by abettermap** [comment]
> Could it be that we need something in AT > Schema 

good hypothesis. it's possible but I think it's most likely something in the code that got lost in the shuffle. i don't use None very often and tend to forget about it, so it might have been broken for some time.

if it's not an easy fix or i can't figure it out quickly, how would you feel about just removing it for the interim? i'll restore it eventually since it worked before, but at least there wouldn't be the full-on brokenness until then.

**Comment by rperlin-ela** [comment]
I do kind of like it sometimes for a cleaner view, but I agree it’s probably not something the masses are going to miss — so for sure remove for the interim if it’s a more involved fix
