### ISSUE TITLE
Symbology disappears when querying/filtering the data

### ISSUE THREAD

**Issue by rperlin-ela** [Language-Mapping/language-map#176]
Throwing myself on the mercy of @abettermap :) I've been able to troubleshoot my way out of most things I've caused, but just been banging my head against this one for hours.

All colored points load normally, and you can visit them one by one or via Omnibox just fine, but when I filter in any way in the UI table they all disappear. World Region, Size, Status, Language, Endonym, nothing shows up, though the map still zooms to the right extent.

I reckon I must have caused this today while doing some data editing, getting ready to send to some beta testers. I don't think it's an MB issue— have tried uploading different old and new tilesets there to no avail. So I assume it's something in Airtable, maybe something as tiny as a space or a line or a missing minus sign or a duplicate ID, but QC shows no problems and I've looked in every way I can think of. I hope it's not something painfully obvious that I'm just not seeing— I'm guessing given the fields involved that it's something to do with the "Data" table.

Wasn't sure if there's a safe way to use AT's Snapshot feature to troubleshoot/restore in a case like this. I tried some Undo'ing and restored a version that I thought might be pre-bug in AT, but I wasn't sure what I should do with it if you're still hitting the main base. Download and import the old version as a spreadsheet into the main base to replace what's there? A clear workflow for restoring with a Snapshot could be useful in general for troubleshooting.

**Comment by abettermap** [comment]
Hmm interesting. I can take a peek at AT tomorrow and give the Chrome console a skim for errors in the map.

**Comment by rperlin-ela** [comment]
Thanks!!

**Comment by abettermap** [comment]
See my comment here https://github.com/Language-Mapping/language-map/issues/147#issuecomment-771031688 and if that fixes this then let's close it.

Re: AT's Snapshot feature, I'm not sure. On my end it's the usual requirements- schema and data types should be consistent. That's it.

**Comment by rperlin-ela** [comment]
Ok, just one question — your code is hitting a URL specific to this base, right? It’s not like I can create a new base (or have one generated by Snapshot), name it ELA Data in Airtable, delele the old one, and the code can still hit it?

**Comment by abettermap** [comment]
Correct, code hits a specific base. If a new base were created and it had an identical schema (table names, col names, data types, etc.) then yeah I would just need the new API base ID. I'd have to double-check but I don't think that's in code at all, it's an environment variable, so I'd just have to update Netlify and maybe GH settings.

Why would you want to do that though?

**Comment by rperlin-ela** [comment]
Unlike with Google Sheets’ restore feature, AT insists on creating a separate new base with Snapshot. So with Sheets I could see in an instant whether a problem persists by temporarily restoring an older version, whereas it seems like a substantial workaround with AT

**Comment by abettermap** [comment]
Wow that's not very ideal. 

If what you're suggesting is of interest, I could confirm that the code doesn't reference the API base id directly then document the steps to change it. In a nutshell:

1. log into Netlify
2. change the environment variable
3. rebuild/deploy the project

steps 1-2 take seconds, 3 takes a few minutes. 

Straightforward but you'd have to let me know each time you do it so that I can change the environment variable in my local environment as well.

**Comment by rperlin-ela** [comment]
Don’t mind those steps, but I don’t like having to bother you each time. Was hoping to use this as a kind of Undo-to-the-last-time-it-was-working. 

For instance, I restored the last snapshot from when I think (but not sure) that everything might have last been working. It’s sitting in AT right now as a separate base if we want to test it. And there are a number of other Snapshots to try.

**Comment by abettermap** [comment]
> Don’t mind those steps, but I don’t like having to bother you each time.

I think we could avoid that if I just remind myself to grab the AT ID from Netlify each time. It would get _really_ confusing if I forget (since I would be seeing old data, or it maybe it would fail entirely if you deleted the old base), but at least it's directly linkable (we'll have to get you the creds to see it): https://app.netlify.com/sites/languagemapping/settings/deploys#environment-variables

I might be able to automate somehow but if not then it's fine to do occasionally. For active daily development though it would be very annoying and error-prone though so I don't think that's a good workflow.

**Comment by abettermap** [comment]
@rperlin-ela did we resolve this? If I recall, it was an AT thing that we fixed. If so, please close.
