### ISSUE TITLE
Feedback form at "Details" and "Language profile"

### ISSUE THREAD

**Issue by rperlin-ela** [Language-Mapping/language-map#205]
Create a prominent link to the feedback form at bottom of the “Details” and “Language profile” views using a style button or prominent link element, and add basic supplemental text if needed.

In terms of the latter, some disclaimer like the following would be ideal:

"Note that [Lang Name] may be spoken throughout the New York area — this is just one significant location. Submit your feedback." (where the second bit could be in button form?)

**Comment by abettermap** [comment]
> "Note that [Lang Name] may be spoken throughout the New York area — this is just one significant location. Submit your feedback."

does this still apply to Lang Profile or only Details? 

for that matter, where should it be included besides Details? i could see including it in Lang Profile at the /Explore/Something/Something/LangName but not at /Explore/Language/LangName. 

if we ARE including it at more than just Details (which is how i worded in SOW but maybe it's not applicable), let me know the wording for non-Details supplemental text.

if it matters, keep in mind we'll likely have another Feedback Link sprinkle in the catch-all menu. so, as a user my vote would probably be only include it in Details with the supplemental wording, and then either exclude it from all other views, or put it most or all of them at the bottom, but w/more generic text than what we'd use for Details.

**Comment by rperlin-ela** [comment]
The question is how to sprinkle generously without overloading, and I’m open to different options. The supplemental text may be needed only for Details and maybe just ”Submit your feedback” will be sufficient for Lang Profile

**Comment by abettermap** [comment]
ok. i think the "outlined" button variant is pretty non-overloady, so we'll start there.

clarify please, for feedback link btn:

1. Details (YES)
2. Lang profile: only non-`/Explore/Language/LangName`, or **that one too**?

### popups link
Related: SOW says: 

> Map popups: include a feedback link at the bottom of all popups if it looks relevant in this context.

i think we (or I) just kinda threw that one in there, but with all the other sprinkles, the popup sounds overloady to me. not to mention, since we're moving forward w/the "more routes and nesting panelage" approach, it's less necessary to cram things into the lil' popups, so **can we scrap that SOW item (2.3.2)?**

keep in mind verrrrrry few people are going to provide feedback no matter how many sprinkles you put on this UI donut. so i think:

`best use of time + less potential annoyance to users = no feedback link in popups.`

**Comment by rperlin-ela** [comment]
What was the thinking for not including at /Explore/Language/LangName? Mind working a little slow at the moment, would probably just say Details and Lang Profile both. But I think I agree on the pop-up, we can scrap that. I know we won’t necessarily get tons of feedback, but providing the option is important adn the disclaimer is important too

**Comment by abettermap** [comment]
> What was the thinking for not including at /Explore/Language/LangName

i think i was just hung up on the specific supplemental text, but since we're not using that for either of the Lang Profiles now, it makes sense to include in both.

**Comment by abettermap** [comment]
sufficient in details?

![image](https://user-images.githubusercontent.com/4974087/112702740-327a2a80-8e5a-11eb-8c3b-eb0ee6eebfcf.png)

or subtle outline? i like this better but not married to either and am open non-buttony too (like no fill or outline or shadow, just the text and icon):

![image](https://user-images.githubusercontent.com/4974087/112703028-1b880800-8e5b-11eb-8d2a-cad17bfc474f.png)

and here it is on lang profile:

![image](https://user-images.githubusercontent.com/4974087/112703178-9b15d700-8e5b-11eb-934d-95e7a617f998.png)


FYI it opens to a modal from both details and lang profile. couldn't get scroll-to-the-form to work inside that panel on mobile. so modal = nuclear easy. it's the same modal we have now in prod.

i left it as-is in /Info/Feedback though. it's totally fine on its own in there and there's not as compelling a reason to stay in the same view (/Info) as there is in details or lang profile. modal also seems overkill for a feedback form when you're already coming from an Info-like view. 

any wording or style changes to any of the scenarios, let me know. would prefer not to de-panel-view the current in-panel /Info/Feedback form is all.

**Comment by rperlin-ela** [comment]
Need to change one word here, my bad, to cover sign language(s) and liturgical ones:

"may be used” instead of “may be spoken"

**Comment by abettermap** [comment]
your baby now! https://github.com/Language-Mapping/language-map/pull/213

before you ask for dynamic text on this one (the language-specific reference in details), please keep in mind that i've just added the ability for you to control just about any bit of text in the UI now. we've lost many hours on the back and forth of these little things, or days over the course of the project if we're being honest, so i hope that what i implemented tonight will heal that painful process and save us both a lot of time and hassle by giving you 100% control over these contentious bits of text that are so prone to change. 

i don't think we're going to lose/confuse any users with something generic like this:

![image](https://user-images.githubusercontent.com/4974087/112742503-41d9a080-8f4c-11eb-8bb6-2b8c2e4ef372.png)

...as opposed to specifying the language. so unless anyone mentions otherwise, let's keep it generic and call it a fair trade for the text control you now have for the 14 pieces of UI i added tonight, and whatever other ones you want in the next week.  super easy to set up on my end now!
