### ISSUE TITLE
Welcome Screen keeps reappearing in Info

### ISSUE THREAD

**Issue by rperlin-ela** [Language-Mapping/language-map#219]
Not a major thing, but for those brave souls who choose "Show on Startup" for the Welcome Screen, everything seems to work fine except the Info panel, where clicking on any level or anchor seems to prompt the Welcome Screen to re-appear, as if we've left the site (becuase we're actually going to Wordpress?).

**Comment by abettermap** [comment]
I think the obvious solution is to include some welcome text that says USE AT YOUR OWN RISK 😆 

Jk i'll fix this next week, sounds easy at first glance. ￼

**Comment by abettermap** [comment]
@rperlin-ela something to watch out for in AT paragraphs:

![image](https://user-images.githubusercontent.com/4974087/113616587-86cb9a00-9612-11eb-9278-2f29e7515249.png)

make sure not to **bold** or _italicize_ the preceding space before the text you want to format (you don't want that space formatted anyway, even in a Word doc), otherwise markdown can't hang:

![image](https://user-images.githubusercontent.com/4974087/113616781-c7c3ae80-9612-11eb-8395-e29f055fe54a.png)

**Comment by rperlin-ela** [comment]
Clutch, thanks
