### ISSUE TITLE
Search panel opening issue when scrolled down in panel

### ISSUE THREAD

**Issue by rperlin-ela** [Language-Mapping/language-map#239]
Came across in longer descriptions (which I'm trying to trim back) e.g. Argentine Spanish. When I scroll down and then click to open the search panel (magnifying glass), it doesn't open but just bumps me a little bit in the description. Seems to be on both mobile and desktop.

**Comment by abettermap** [comment]
It's because the search tabs are at the top of the panel. It would have to scroll the panel back to the top when you click the button. 

I've been thinking about a different approach though, like making it appear on top of the rest of the stuff in the panel on non-Home views. This might help the fix￼￼ for the other related issue of not seeing the Search Locations results. 

I don't want this to get out of hand though, because it would require different styling since the Home panel is different in that the search tabs have to stay statically positioned rather than floating on top. Will look into it though.￼
