### ISSUE TITLE
The word "table" on the Data panel

### ISSUE THREAD

**Issue by rperlin-ela** [Language-Mapping/language-map#250]
Tiny pet peeve here, but when the Data table opens up "full screen" I still see and can't quite unseen the word "table" behind it back on the panel itself. Any word to axe it or make it read "Data"?

**Comment by abettermap** [comment]
ha i was just noticing that tonight. yeah easy fix, i just have all the panel titles based on the route. 

the easiest fix would just be to rename the route to `/Data` instead of `/table`, as well as its child route to `/Data/:id` (when full screen Details view is shown via table).

any problems with that?

**Comment by abettermap** [comment]
actually it doesn't make sense to have a panel title at all, so i'll just hide it. speaking of panel titles though, i'd like to see them in ALL views. will start a new issue w/some ideas, and it's a good segway from this thread.

**Comment by rperlin-ela** [comment]
Good, cool. Yeah, good discussion to have. Still also rethinking a few of those names we just kind of threw in — can discuss in the new thread
