### ISSUE TITLE
Making geocoder point label go away

### ISSUE THREAD

**Issue by rperlin-ela** [Language-Mapping/language-map#252]
Sorry if this has come up somewhere before, but when a location search brings us to a point and labels it, we can clear the point  itself by clicking the x at the right end of the search bar. But the label sticks around — any way to axe?

**Comment by abettermap** [comment]
ugh yeah this is annoying, i'm not sure why it hides the marker but not the label, they're all part of the same component.

will take a look though...

**Comment by abettermap** [comment]
i got this to work but there are a lot of scenarios around it (nothing new, same as before, just more apparent now that the clear works better). for example, how long should the marker and label stay around? like if i go to another view/panel/route, should it close? should opening the Search popout from a non-Home clear it? 

nuclear and heavy-handed are the easy approaches and i don't want to go down any other roads since this isn't a new problem, but one thing to make life easier is if i just use a popup instead. hard to explain why but does this work for you?

![image](https://user-images.githubusercontent.com/4974087/113946607-0baae500-97c6-11eb-89b3-e50a28d55e77.png)

**Comment by abettermap** [comment]
its X doesn't clear the geocoder, but at least it gets the popup out of the way and leaves geocoder intact.

and i guess i could make it clear the popup on any map click instead of on route change? feels fine to me now that the X is there. marker didn't have it.

**Comment by rperlin-ela** [comment]
closeable popup seems good. and maybe clearing the popup on map click, your call
