### ISSUE TITLE
Info panel tweaks

### ISSUE THREAD

**Issue by rperlin-ela** [Language-Mapping/language-map#259]
Sorry if I missed this or we discussed this, which is likely, but why did we axe the panel header text within Info? Especially important for Help and About, but might as well Contact and Feedback. Maybe I can adjust the Google Form if it feels too redundant.

Also the anchors needing to be clicked twice in Help and About, since first time does nothing. Apologies if I already made an issue for it but I couldn't find it just now. This is almost as painful as the old X closing problem on Help— I kinda feel like scrapping the anchors if we can't fix.

**Comment by abettermap** [comment]
> but why did we axe the panel header text within Info?

got lost in the shuffle. will add/restore.

> Also the anchors needing to be clicked twice in Help and About, since first time does nothing. 

not sure i can reproduce this. when i click "Credits" for example, it takes me to that section.

**Comment by rperlin-ela** [comment]
Can you try a fresh load or a private window? It’s like you need to click once on an anchor, and it does nothing, but the next time it goes to the right place.

**Comment by abettermap** [comment]
the "Back to top" btn doesn't show in that scenario, so that's a bug. tried to fix already but guess not.

AH, here's your problem, at least for this one: 

your Map Options anchor points to and id with `mapoptions`: _/Info/Help#mapoptions_

but the section actually has an id of `details`:

![image](https://user-images.githubusercontent.com/4974087/114192968-4ff3cd80-990b-11eb-9d36-86f65b7d0c61.png)

**Comment by rperlin-ela** [comment]
Good catch, thanks, just fixed. From yesterday’s Help editing! But I think it’s broader issue. Actually what happens precisely is that for a fraction of a second it does go to the right place (the anchor) but then it bounces me back to the top again

Back to Top btn still goes away (and stays away) if I hit the very bottom

**Comment by abettermap** [comment]
Ah I can reproduce this on mobile. 

Did you change your screenshots and use an iPad like I suggested? They are looking _crisp_!￼

**Comment by rperlin-ela** [comment]
I tried to improve them, but actually Julia is supposed to go through and re-do the screenshots (for this and manual), so hopefully will be even better

**Comment by abettermap** [comment]
> Sorry if I missed this or we discussed this, which is likely, but why did we axe the panel header text within Info? Especially important for Help and About, but might as well Contact and Feedback. Maybe I can adjust the Google Form if it feels too redundant.

there are now about a dozen overrides to the otherwise-consistent URL-driven panel titles, so let's try to just be okay with that before requesting additional overrides. it was a little mess to begin with, but now it's a lot of messy. will change this one but i don't think "Feedback" as the panel title would've been bad.

**Comment by rperlin-ela** [comment]
Feedback is fine
