### ISSUE TITLE
Macrocommunities separated from icon on wide screen

### ISSUE THREAD

**Issue by rperlin-ela** [Language-Mapping/language-map#265]
I have a pretty wide monitor but I now see a breakpoint for Explore which wasn't there before merge as I make the screen wider, such that the card for Macrocommunities goes on a different line from its icon. I know the whole thing is tricky and that it's good for most sizes, but maybe it was better how it was

_Originally posted by @rperlin-ela in https://github.com/Language-Mapping/language-map/issues/261#issuecomment-818062720_

**Comment by abettermap** [comment]
this one drives me nuts, it's on a lot of different sizes. what i ended up doing for the "XL" screens:

![image](https://user-images.githubusercontent.com/4974087/114483673-08e53100-9bc6-11eb-95dc-0959c4bbc905.png)

which is fine i guess, although it would've been nice to have 3-column grid for this:

![image](https://user-images.githubusercontent.com/4974087/114483736-21ede200-9bc6-11eb-9408-413bf37e891d.png)

and no i'm not going to customize it for each view, ha

looks fine on my laptop at 1290ish px:

![image](https://user-images.githubusercontent.com/4974087/114484146-e7387980-9bc6-11eb-99c7-b436d3d6ce26.png)

ideally it would just ellipsize, but then that makes Language Families do the same even though it should wrap.

just not a lot of space in sidebar, hard to work with w/o making it super crowded. still wraps on phone:

![image](https://user-images.githubusercontent.com/4974087/114484493-8f4e4280-9bc7-11eb-8b70-d86213bef7b5.png)

but i don't want to ellipsize it because then we'll lose hundreds of two-liners like these guys:

![image](https://user-images.githubusercontent.com/4974087/114484612-c9b7df80-9bc7-11eb-9f20-0f4c992350aa.png)

so i'd rather just eat it on mobile for the ultra-long single-worders. if solution arrives some day, awesome.
